### ISSUE TITLE
following erroe occurede  while running 

### ISSUE THREAD

**Issue by rrishabhj** [MayankPratap/show-down#48]
I M USING UBUNTU

Traceback (most recent call last):
  File "episode.py", line 1, in <module>
    from showDown import showDown
  File "/home/rishabh/github/show-down/showDown/showDown.py", line 27
    """
      ^
IndentationError: expected an indented block

**Comment by MayankPratap** [comment]
@rrishabhj  Sorry for late reply , we had stopped working on this project. Please try again and notify if problem persists.
